[project]
name = "aipm-voice-data-worker"
version = "0.0.0"
description = ""
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.110.0",
]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["main"]
