services:
  aipm-pg:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: aipm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - aipm-database:/data
    ports:
      - '5432:5432'
    networks:
      - aipm-network

  aipm-nats:
    image: nats:2.14.2-alpine3.22
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - aipm-nats:/nats/storage
    networks:
      - aipm-network
    restart: unless-stopped

  aipm-text-data-worker:
    build:
      context: .
      dockerfile: apps/text-data-worker/Dockerfile
    env_file:
      - apps/text-data-worker/.env
    volumes:
      - aipm-text-data-worker-context:/data
    networks:
      - aipm-network
    depends_on:
      - aipm-pg
      - aipm-nats
    restart: unless-stopped

  aipm-web-chat:
    build:
      context: .
      dockerfile: apps/web-chat/Dockerfile
    environment:
      NATS_HOST: aipm-nats
      NATS_PORT: "4222"
      DATABASE_URL: postgresql://postgres:password@aipm-pg:5432/aipm
    ports:
      - "8080:8080"
    networks:
      - aipm-network
    depends_on:
      - aipm-pg
      - aipm-nats
    restart: unless-stopped

volumes:
  aipm-database:
    name: aipm-database
  aipm-nats:
    name: aipm-nats
  aipm-text-data-worker-context:
    name: aipm-text-data-worker-context

networks:
  aipm-network:
    name: aipm-network
    driver: bridge
